---
- name: Deploy image to openstack and create instance
  hosts: localhost
  vars:
    admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30323961373332656639663834643533346631396634663634383532666331653065356638373761
          6130636365643263323936643539613432306538306131610a316463326138333534363262303430
          34393935363934313933366139303836356236353530303939303364323136643763356361323434
          3330303464306530620a666166303536363737656332333436346263613964646261383062633363
          6231
  tasks:
  - name: Downloading ubuntu cloud image 
    get_url:
      url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
      dest: /tmp/bionic.img

  - name: Uploading image to openstack
    os_image:
      auth:
         auth_url: http://10.1.29.40/identity
         username: admin
         password: "{{ admin_password }}"
         project_name: admin
         os_user_domain_name: Default
         os_project_domain_name: Default
      name: bionic
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/bionic.img

  - name: Creating SSH keypair
    os_keypair:
      auth:
         auth_url: http://10.1.29.40/identity
         username: admin
         password: "{{ admin_password }}"
         project_name: admin
         os_user_domain_name: Default
         os_project_domain_name: Default
      state: present
      name: ubuntu
      public_key_file: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"

  - name: Creating the instance
    os_server:
      auth:
         auth_url: http://10.1.29.40/identity
         username: admin
         password: "{{ admin_password }}"
         project_name: admin
         os_user_domain_name: Default
         os_project_domain_name: Default
      state: present
      name: bionic
      image: bionic
      flavor: m1.small
      security_groups: default
      key_name: ubuntu
      nics:
        - net-id: 4c3f1cc5-c466-4e84-86b4-cafbd8367e9a
    register: bionic

  - name: Adding instance to inventory
    add_host: 
      name: '{{ bionic.openstack.public_v4 }}' 
      groups: linux

  - name: Waiting for the SSH-server on instance
    wait_for:
       port: 22
       host: '{{ bionic.openstack.public_v4 }}'
       search_regex: OpenSSH
       delay: 10
       timeout: 120

- name: Creating user accounts, SSH-keys and copy repository-files
  hosts: linux
  tasks:
  - include_vars: users.yml
  - name: Creating users
    user: name="{{ item.username }}" shell=/bin/bash createhome=yes group=sudo
    with_items: "{{ users }}"

  - name: Placing SSH Key to Authorized Key
    authorized_key: user="{{ item.username }}" key="{{ lookup('file', './keys/authorized_keys.{{ item.username}}.pub') }}"
    with_items: "{{ users }}"

  - name: Updating sudoers file
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      regexp='^{{ item.username }} .*'
      state=present"
    with_items: '{{ users }}'

  - name: Copying ppa-files
    copy:
      src: "{{ item }}"
      dest: "/etc/apt/sources.list.d/"
    with_fileglob:
      - "./repositories/*"
